version: "3.8"

services:

  mysql:
    image: mysql:8.0
    container_name: mysql-docker
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gestion_client
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  api:
    build: .
    container_name: gestion-client-api
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/gestion_client
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8080:8080"
    restart: always

volumes:
  mysql-data:
