apiVersion: apps/v1
kind: Deployment
metadata:
  name: gestion-client-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gestion-client-api
  template:
    metadata:
      labels:
        app: gestion-client-api
    spec:
      containers:
        - name: gestion-client-api
          image: zahralassri/gestion-client-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/gestion_client
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: root
