apiVersion: v1
kind: Service
metadata:
  name: gestion-client-api-service
spec:
  type: NodePort
  selector:
    app: gestion-client-api
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
